#Hugo configuration
title = "wqrsdgf"
baseURL = "https:\/\/dfg.sdf.wer"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
reservedContent = "test.md,protected/"
